version: "3"

services:
    elixir:
        build: .
        restart: always
        ports:
            - "30000:80"
        environment:
            - GIT_REPO_URL=git://git.musl-libc.org/musl
            - PROJECT=musl
